### ISSUE TITLE
Disable swipe/scrolling between each page?

### ISSUE THREAD

**Issue by Linspirit98** [Crazelu/linear-step-indicator#1]
How can i disable swipe/scrolling between each page? This doesn't seem to have an option for physics.

**Comment by Crazelu** [comment]
I believe you're trying to use the StepIndicatorPageView.
That's a good catch. I'll add support for ScrollPhysics in a bit.

Or you can beat me to it and submit a PR 😌

**Comment by Crazelu** [comment]
Support for ScrollPhysics is now available in linear_step_indicator 1.0.0+3 
Cheers!

**Comment by Linspirit98** [comment]
> Support for ScrollPhysics is now available in linear_step_indicator 1.0.0+3 Cheers!

Thank you so much! Lovely change~
